// src/ninja.rs
//
// Steel — Ninja file generation
//
// This module converts a simple target file into a Ninja build graph.
// It is intentionally minimal and deterministic.

use std::collections::BTreeMap;
use crate::target_file::{TargetFile, TargetSpec};

#[derive(Debug)]
pub enum NinjaError {
    MissingOutput(String),
}

impl std::fmt::Display for NinjaError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            NinjaError::MissingOutput(name) => write!(f, "target `{name}` missing output (out ...)"),
        }
    }
}

impl std::error::Error for NinjaError {}

pub fn render_ninja(tf: &TargetFile) -> Result<String, NinjaError> {
    let mut out = String::new();
    out.push_str("# build.ninja generated by steel\n");
    out.push_str("ninja_required_version = 1.3\n\n");
    out.push_str("rule run\n");
    out.push_str("  command = $cmd\n");
    out.push_str("  description = $desc\n");
    out.push_str("  restat = 1\n\n");

    let outputs = target_outputs(tf)?;

    for t in &tf.targets {
        let out_path = outputs.get(&t.name).expect("output map");
        let inputs = build_inputs(t, &outputs);
        let cmd = command_for_target(t, out_path);

        if let Some(cmd) = cmd {
            out.push_str(&format!(
                "build {}: run {}\n",
                escape_path(out_path),
                join_paths(&inputs)
            ));
            out.push_str(&format!("  cmd = {}\n", escape_value(&cmd)));
            out.push_str(&format!("  desc = {}\n", escape_value(&t.name)));
        } else {
            out.push_str(&format!(
                "build {}: phony {}\n",
                escape_path(out_path),
                join_paths(&inputs)
            ));
        }
        out.push('\n');
    }

    if !tf.targets.is_empty() {
        let mut defaults = Vec::new();
        for t in &tf.targets {
            if let Some(out_path) = outputs.get(&t.name) {
                defaults.push(out_path.clone());
            }
        }
        out.push_str(&format!("default {}\n", join_paths(&defaults)));
    }

    Ok(out)
}

fn target_outputs(tf: &TargetFile) -> Result<BTreeMap<String, String>, NinjaError> {
    let mut map = BTreeMap::new();
    for t in &tf.targets {
        let out = t
            .out
            .clone()
            .unwrap_or_else(|| format!("build/{}", t.name));
        map.insert(t.name.clone(), normalize_path(&out));
    }
    Ok(map)
}

fn build_inputs(t: &TargetSpec, outputs: &BTreeMap<String, String>) -> Vec<String> {
    let mut inputs = Vec::new();
    for src in &t.sources {
        inputs.push(normalize_path(src));
    }
    for dep in &t.deps {
        if let Some(out) = outputs.get(dep) {
            inputs.push(out.clone());
        }
    }
    inputs
}

fn command_for_target(t: &TargetSpec, out_path: &str) -> Option<String> {
    if let Some(cmd) = t.meta.get("cmd") {
        return Some(cmd.clone());
    }
    if let Some(tool) = t.meta.get("tool") {
        let mut parts = Vec::new();
        for (k, v) in &t.env {
            parts.push(format!("{k}={v}"));
        }
        parts.push(tool.clone());
        for (k, v) in &t.defines {
            parts.push(format!("-D{}={}", k, v));
        }
        parts.extend(t.args.iter().cloned());
        if !out_path.trim().is_empty() {
            parts.push("-o".to_string());
            parts.push(out_path.to_string());
        }
        parts.extend(t.sources.iter().cloned());
        return Some(parts.join(" "));
    }
    None
}

fn normalize_path(s: &str) -> String {
    s.replace('\\', "/")
}

fn escape_value(s: &str) -> String {
    s.replace('$', "$$")
}

fn escape_path(s: &str) -> String {
    let mut out = String::new();
    for ch in s.chars() {
        match ch {
            ' ' => out.push_str("$ "),
            ':' => out.push_str("$:"),
            '$' => out.push_str("$$"),
            c => out.push(c),
        }
    }
    out
}

fn join_paths(paths: &[String]) -> String {
    let mut out = String::new();
    for (i, p) in paths.iter().enumerate() {
        if i > 0 {
            out.push(' ');
        }
        out.push_str(&escape_path(p));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::target_file::{parse_target_file_str, ParseOptions};

    #[test]
    fn render_basic_ninja() {
        let src = r#"
target app
  kind exe
  out build/app
  src src/main.c
  deps core
  args -O2
  tool gcc
.end
target core
  kind staticlib
  out build/libcore.a
  src src/core.c
  tool gcc
.end
"#;
        let tf = parse_target_file_str(src, &ParseOptions::default()).unwrap();
        let ninja = render_ninja(&tf).unwrap();
        assert!(ninja.contains("rule run"));
        assert!(ninja.contains("build build/app: run"));
        assert!(ninja.contains("build build/libcore.a: run"));
        assert!(ninja.contains("default"));
    }
}
